import entity from '@/ts/entity';
import type { DynamicObject } from '@/types/common';
import type { Card, CardRef } from '@/types/card';
import { deepMerge } from '@/helpers';

export const getCardsByElement = (cards: [string, Card][]) =>
  cards.reduce(
    (a, card) => ({
      ...a,
      [card.element]: [...(a[card.element] || []), card]
    }),
    {}
  );

const DEFAULT_COST = undefined;

export const ALL_CARDS = {
  ragnar: {
    name: 'Ragnar',
    image: 'creature/fire/ragnar-god-of-fire.jpg',
    element: 'fire',
    icon: 'fire',
    cost: DEFAULT_COST,
    type: 'god',
    subtypes: ['fire'],
    keywords: [],
    text: 'Friendly units that arrived this turn has +1 damage.',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 3,
    damage: 0,
    health: 0
  },
  fireball: {
    name: 'Scorchling',
    image: 'creature/fire/scorchling.jpg',
    element: 'fire',
    icon: 'fire',
    cost: 2,
    type: 'unit',
    subtypes: ['elemental'],
    keywords: ['wildfire', 'aggressive'],
    text: '',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 1,
    damage: 1,
    health: 2
  },
  cerberus: {
    name: 'Cerberus',
    image: 'creature/fire/cerberus.jpg',
    element: 'fire',
    icon: 'fire',
    cost: 6,
    type: 'unit',
    subtypes: ['hound', 'dweller'],
    keywords: ['triple-strike'],
    text: '',
    flavourText: 'This ferious beast makes you look t.. thrice!',
    internalNote: '',
    aiPrompt: '',
    rarity: 2,
    damage: 1,
    health: 4
  },
  monsIgneus: {
    name: 'Mons Igneus',
    image: 'creature/fire/mons-igneus.jpg',
    element: 'fire',
    icon: 'fire',
    cost: 10,
    type: 'unit',
    subtypes: ['dragon'],
    keywords: ['flying'],
    text: 'When this unit arrives, deal its damage to target unit.',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 4,
    damage: 6,
    health: 10
  },
  oskar: {
    name: 'Oskar',
    image: 'creature/lightning/oskar-god-of-lightning.jpg',
    element: 'lightning',
    icon: 'lightning',
    cost: DEFAULT_COST,
    type: 'god',
    subtypes: ['lightning'],
    keywords: [],
    text: 'I always start the game.',
    flavourText: '',
    internalNote: `Yet another lightning bolt strikes the top of the mountain. A mad-man appears. He refers to himself as, 'God of Lightning.'<br /><br />"Mwhahaha, it tickles!"`,
    aiPrompt: '',
    rarity: 3,
    damage: 0,
    health: 0
  },
  shockling: {
    name: 'Shockling',
    image: 'creature/lightning/shockling.jpg',
    element: 'lightning',
    icon: 'lightning',
    cost: 2,
    type: 'unit',
    subtypes: ['elemental'],
    keywords: ['tempest', 'swift'],
    text: '',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 1,
    damage: 1,
    health: 2
  },
  lightingGiant: {
    name: 'Giant',
    image: 'creature/lightning/giant.jpg',
    element: 'lightning',
    icon: 'lightning',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['giant'],
    keywords: [],
    text: '',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 3,
    damage: 0,
    health: 0
  },
  ventoMico: {
    name: 'Vento Mico',
    image: 'creature/lightning/vento-mico.jpg',
    element: 'lightning',
    icon: 'lightning',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['dragon'],
    keywords: ['flying', 'swift'],
    text: '',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 4,
    damage: 0,
    health: 0
  },
  alora: {
    name: 'Alora',
    image: 'creature/nature/alora-goddess-of-nature.jpg',
    element: 'nature',
    icon: 'nature',
    cost: DEFAULT_COST,
    type: 'god',
    subtypes: ['nature'],
    keywords: [],
    text: 'Whenever a friendly immortal is reborn, I heal a target friendly unit for 1.',
    flavourText: '',
    internalNote:
      'A soft breeze stirs the leaves, and the forest seems to breathe. A gentle figure steps forward, smiling kindly. She is known as "Mother of Nature."',
    aiPrompt: '',
    rarity: 3,
    damage: 0,
    health: 0
  },
  healling: {
    name: 'Healling',
    image: 'creature/nature/healling.jpg',
    element: 'nature',
    icon: 'nature',
    cost: 2,
    type: 'unit',
    subtypes: ['elemental'],
    keywords: ['overgrowth', 'regenerative'],
    text: '',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 1,
    damage: 2,
    health: 2
  },
  eratHerba: {
    name: 'Erat Herba',
    image: 'creature/nature/erat-herba.jpg',
    element: 'nature',
    icon: 'nature',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['dragon'],
    keywords: ['flying', 'aggressive', 'swift'],
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 4,
    damage: 0,
    health: 0
  },
  verdantStag: {
    name: 'Verdant Stag',
    image: 'creature/nature/verdant-stag.jpg',
    element: 'nature',
    icon: 'nature',
    cost: 3,
    type: 'unit',
    subtypes: ['beast'],
    keywords: ['swift', 'regenerative'],
    text: '',
    flavourText: 'Where the stag walks, the forest blooms.',
    internalNote: '',
    aiPrompt:
      'A majestic forest stag with glowing green antlers covered in vines and flowers, moss and leaves growing on its body, ethereal green mist surrounding it, standing proudly in an ancient forest, sunlight filtering through trees, bioluminescent plants glowing around it, epic fantasy creature art, highly detailed digital painting, mystical forest lighting, serene and powerful, no text',
    rarity: 2,
    damage: 2,
    health: 3
  },
  ironbarkTreant: {
    name: 'Ironbark Treant',
    image: 'creature/nature/ironbark-treant.jpg',
    element: 'nature',
    icon: 'nature',
    cost: 7,
    type: 'unit',
    subtypes: ['treant'],
    keywords: ['sturdy', 'regenerative'],
    text: '',
    flavourText: 'Ancient as the forest itself, patient as the seasons.',
    internalNote: '',
    aiPrompt:
      'A massive ancient treant with thick bark-covered body, roots as legs, branches as arms with glowing green leaves, wise glowing eyes in the trunk, mushrooms and vines growing on its body, standing in a mystical forest, magical green energy emanating from it, moss-covered stones around it, epic fantasy creature art, highly detailed digital painting, magical forest lighting, ancient and powerful, no text',
    rarity: 3,
    damage: 3,
    health: 7
  },
  bloomwisp: {
    name: 'Bloomwisp',
    image: 'creature/nature/bloomwisp.jpg',
    element: 'nature',
    icon: 'nature',
    cost: 1,
    type: 'unit',
    subtypes: ['spirit', 'elemental'],
    keywords: ['flying', 'overgrowth'],
    text: '',
    flavourText: 'A whisper of life on the wind.',
    internalNote: '',
    aiPrompt:
      'A small ethereal nature sprite made of swirling green energy and flower petals, translucent glowing form, trailing magical sparkles, delicate wings made of leaves and light, playful expression, floating above wildflowers in a sunlit forest glade, butterflies and fireflies around it, epic fantasy creature art, highly detailed digital painting, soft magical lighting, whimsical and enchanting, no text',
    rarity: 1,
    damage: 1,
    health: 1
  },
  kyl: {
    name: 'Kyl',
    image: 'creature/frost/kyl-god-of-frost.jpg',
    element: 'frost',
    icon: 'frost',
    cost: DEFAULT_COST,
    type: 'god',
    subtypes: ['frost'],
    keywords: [],
    text: 'Whenever an enemy unit hurts me the turn it arrived, I permanently freeze it.',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 3,
    damage: 0,
    health: 0
  },
  freezeling: {
    name: 'Freezeling',
    image: 'creature/frost/freezeling.jpg',
    element: 'frost',
    icon: 'frost',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['elemental'],
    keywords: ['flashfreeze', 'still'],
    text: '',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 1,
    damage: 1,
    health: 2
  },
  frigus: {
    name: 'Frigus Mortis',
    image: 'creature/frost/frigus-mortis.jpg',
    element: 'frost',
    icon: 'frost',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['dragon'],
    keywords: ['flying'],
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 4,
    damage: 0,
    health: 0
  },
  hammersnout: {
    name: 'Hammersnout',
    image: 'creature/frost/hammersnout.jpg',
    element: 'frost',
    icon: 'frost',
    cost: 5,
    type: 'unit',
    subtypes: ['beast', 'aquatic'],
    keywords: ['aggressive'],
    text: '',
    flavourText: "The ocean's hammer strikes without warning.",
    internalNote: '',
    aiPrompt:
      'A fierce hammerhead swordfish creature with a broad hammer-shaped snout, sleek metallic scales with blue and silver tones, swimming in dynamic attacking pose, water splashing around it, glowing bioluminescent patterns on fins, sharp teeth visible, storm clouds and turbulent ocean waves in background, underwater light rays piercing through water, epic fantasy creature art, highly detailed digital painting, dramatic oceanic lighting, powerful and menacing, no text, no titles, no words, artwork only',
    rarity: 2,
    damage: 4,
    health: 3
  },
  apollyon: {
    name: 'Apollyon',
    image: 'creature/void/apollyon.jpg',
    element: 'void',
    icon: 'void',
    cost: DEFAULT_COST,
    type: 'god',
    subtypes: ['void'],
    keywords: [],
    text: "When I'm defeated, I turn target friendly mortal into a god.",
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 3,
    damage: 0,
    health: 0
  },
  drainling: {
    name: 'Drainling',
    image: 'creature/void/drainling.jpg',
    element: 'void',
    icon: 'void',
    cost: 2,
    type: 'unit',
    subtypes: ['elemental'],
    keywords: ['rupture', 'echoing'],
    text: '',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 1,
    damage: 1,
    health: 2
  },
  terram: {
    name: 'Nullius Terram',
    image: 'creature/void/nullius-terram.jpg',
    element: 'void',
    icon: 'void',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['dragon'],
    keywords: ['flying'],
    text: '',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 4,
    damage: 0,
    health: 0
  },
  elise: {
    name: 'Elise',
    image: 'creature/earth/elise-goddess-of-earth.jpg',
    element: 'earth',
    icon: 'earth',
    cost: DEFAULT_COST,
    type: 'god',
    subtypes: ['earth'],
    keywords: [],
    text: 'My armor is equal to the amount of friendly immortals I command.',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 3,
    damage: 0,
    health: 0
  },
  crushling: {
    name: 'Crushling',
    image: 'creature/earth/crushling.jpg',
    element: 'earth',
    icon: 'earth',
    cost: 2,
    type: 'unit',
    subtypes: ['elemental'],
    keywords: ['landslide', 'sturdy'],
    text: '',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 1,
    damage: 1,
    health: 2
  },
  armorillo: {
    name: 'Armorillo',
    image: 'creature/earth/armorillo.jpg',
    element: 'earth',
    icon: 'earth',
    cost: 2,
    type: 'unit',
    subtypes: ['armorillo'],
    keywords: [],
    text: '',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 1,
    damage: 0,
    health: 0
  },

  earthGiant: {
    name: 'Giant',
    image: 'creature/earth/giant.jpg',
    element: 'earth',
    icon: 'earth',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['giant'],
    keywords: [],
    text: '',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 3,
    damage: 0,
    health: 0
  },
  vitaDeserto: {
    name: 'Vita Deserto',
    image: 'creature/earth/vita-deserto.jpg',
    element: 'earth',
    icon: 'earth',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['dragon'],
    keywords: ['flying'],
    text: '',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 4,
    damage: 0,
    health: 0
  },
  herald: {
    name: 'Herald',
    image: 'creature/lightning/herald.jpg',
    element: 'light',
    icon: 'light',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['beast'],
    keywords: [],
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 2,
    damage: 0,
    health: 0
  },
  ulwar: {
    name: 'Ulwar',
    image: 'creature/lightning/ulwar.jpg',
    element: 'dark',
    icon: 'dark',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['werewolf'],
    keywords: [],
    text: '',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 2,
    damage: 0,
    health: 0
  },
  dither: {
    name: 'Dither',
    image: 'creature/void/giant.jpg',
    element: 'dark',
    icon: 'dark',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['giant'],
    keywords: [],
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 3,
    damage: 0,
    health: 0
  },
  bulton: {
    name: 'Bulton',
    image: 'creature/earth/male-01.png',
    element: 'physical',
    icon: 'earth',
    cost: 4,
    type: 'unit',
    subtypes: ['mortal', 'humanoid', 'troll'],
    keywords: ['Single-Strike'],
    text: '',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 1,
    damage: 4,
    health: 2
  },
  steelSword: {
    name: 'Steel Sword',
    image: 'equipment/sword.png',
    element: 'physical',
    icon: '',
    cost: undefined,
    type: 'relic',
    subtypes: ['equipment', 'one-handed'],
    keywords: ['Equip 1', 'Single-Strike'],
    text: '',
    flavourText: '',
    internalNote: '',
    aiPrompt: '',
    rarity: 1,
    damage: 2,
    health: 0
  },
  tidecaller: {
    name: 'Tidecaller',
    image: 'creature/frost/elemental.jpg',
    element: 'frost',
    icon: 'frost',
    cost: 5,
    type: 'unit',
    subtypes: ['merfolk', 'mage'],
    keywords: ['flashfreeze', 'still'],
    text: 'When this unit arrives, draw a card.',
    flavourText: 'The storm answers to those who listen.',
    internalNote: 'Using placeholder - generate unique tidecaller.jpg when API quota available',
    aiPrompt: '',
    rarity: 2,
    damage: 3,
    health: 4
  },
  emberwing: {
    name: 'Emberwing',
    image: 'creature/fire/ember-fiend.jpg',
    element: 'fire',
    icon: 'fire',
    cost: 7,
    type: 'unit',
    subtypes: ['phoenix', 'immortal'],
    keywords: ['flying', 'reborn'],
    text: 'When this unit is defeated, return it to your hand.',
    flavourText: 'From ashes, it rises eternal.',
    internalNote: 'Using placeholder - generate unique emberwing.jpg when API quota available',
    aiPrompt: '',
    rarity: 3,
    damage: 4,
    health: 3
  }
};

const applyScaling = (card: Card) => {
  // Do stuff
  return card;
};

export default (id: string | CardRef, fullBody: boolean = false, meta?: DynamicObject) =>
  applyScaling(
    entity(
      ALL_CARDS,
      typeof id === 'string' ? id : id.id,
      typeof id === 'string' ? undefined : id.uuid,
      fullBody,
      typeof id === 'string'
        ? meta?.overrides
        : meta?.overrides
          ? deepMerge(id.overrides || {}, meta.overrides || {})
          : id.overrides
    ) as Card
  ) as Required<Card>;
