#!/bin/sh
files=$(git diff --cached --name-only --diff-filter=ACMR)
[ -z "$files" ] && exit 0

echo "$files" | xargs bunx prettier --write --ignore-unknown --log-level=warn
echo "$files" | xargs git add
