import entity from '@/ts/entity';
import type { DynamicObject } from '@/types/common';
import type { Card, CardRef } from '@/types/card';
import { deepMerge } from '@/helpers';

export const getCardsByElement = (cards: [string, Card][]) =>
  cards.reduce(
    (a, card) => ({
      ...a,
      [card.element]: [...(a[card.element] || []), card]
    }),
    {}
  );

const DEFAULT_COST = undefined;

export const ALL_CARDS = {
  ragnar: {
    name: 'Ragnar',
    image: 'creature/fire/ragnar-god-of-fire.jpg',
    element: 'fire',
    icon: 'fire',
    cost: DEFAULT_COST,
    type: 'god',
    subtypes: ['fire'],
    keywords: [],
    text: 'Friendly units that arrived this turn has +1 damage.',
    flavourText: '',
    internalNote: '',
    rarity: 3,
    damage: 0,
    health: 0
  },
  fireball: {
    name: 'Scorchling',
    image: 'creature/fire/scorchling.jpg',
    element: 'fire',
    icon: 'fire',
    cost: 2,
    type: 'unit',
    subtypes: ['elemental'],
    keywords: ['wildfire', 'aggressive'],
    text: '',
    flavourText: '',
    internalNote: '',
    rarity: 1,
    damage: 1,
    health: 2
  },
  cerberus: {
    name: 'Cerberus',
    image: 'creature/fire/cerberus.jpg',
    element: 'fire',
    icon: 'fire',
    cost: 6,
    type: 'unit',
    subtypes: ['hound', 'dweller'],
    keywords: ['triple-strike'],
    text: '',
    flavourText: 'This ferious beast makes you look t.. thrice!',
    internalNote: '',
    rarity: 2,
    damage: 1,
    health: 4
  },
  monsIgneus: {
    name: 'Mons Igneus',
    image: 'creature/fire/mons-igneus.jpg',
    element: 'fire',
    icon: 'fire',
    cost: 10,
    type: 'unit',
    subtypes: ['dragon'],
    keywords: ['flying'],
    text: 'When this unit arrives, deal its damage to target unit.',
    flavourText: '',
    internalNote: '',
    rarity: 4,
    damage: 6,
    health: 10
  },
  oskar: {
    name: 'Oskar',
    image: 'creature/lightning/oskar-god-of-lightning.jpg',
    element: 'lightning',
    icon: 'lightning',
    cost: DEFAULT_COST,
    type: 'god',
    subtypes: ['lightning'],
    keywords: [],
    text: 'I always start the game.',
    flavourText: '',
    internalNote:
      "Yet another lightning bolt strikes the top of the mountain. A mad-man appears. He refers to himself as, 'God of Lightning.'<br /><br />“Mwhahaha, it tickles!”",
    rarity: 3,
    damage: 0,
    health: 0
  },
  shockling: {
    name: 'Shockling',
    image: 'creature/lightning/shockling.jpg',
    element: 'lightning',
    icon: 'lightning',
    cost: 2,
    type: 'unit',
    subtypes: ['elemental'],
    keywords: ['tempest', 'swift'],
    text: '',
    flavourText: '',
    internalNote: '',
    rarity: 1,
    damage: 1,
    health: 2
  },
  lightingGiant: {
    name: 'Giant',
    image: 'creature/lightning/giant.jpg',
    element: 'lightning',
    icon: 'lightning',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['giant'],
    keywords: [],
    text: '',
    flavourText: '',
    internalNote: '',
    rarity: 3,
    damage: 0,
    health: 0
  },
  ventoMico: {
    name: 'Vento Mico',
    image: 'creature/lightning/vento-mico.jpg',
    element: 'lightning',
    icon: 'lightning',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['dragon'],
    keywords: ['flying', 'swift'],
    text: '',
    flavourText: '',
    internalNote: '',
    rarity: 4,
    damage: 0,
    health: 0
  },
  alora: {
    name: 'Alora',
    image: 'creature/nature/alora-goddess-of-nature.jpg',
    element: 'nature',
    icon: 'nature',
    cost: DEFAULT_COST,
    type: 'god',
    subtypes: ['nature'],
    keywords: [],
    text: 'Whenever a friendly immortal is reborn, I heal a target friendly unit for 1.',
    flavourText: '',
    internalNote:
      'A soft breeze stirs the leaves, and the forest seems to breathe. A gentle figure steps forward, smiling kindly. She is known as “Mother of Nature.”',
    rarity: 3,
    damage: 0,
    health: 0
  },
  healling: {
    name: 'Healling',
    image: 'creature/nature/healling.jpg',
    element: 'nature',
    icon: 'nature',
    cost: 2,
    type: 'unit',
    subtypes: ['elemental'],
    keywords: ['overgrowth', 'regenerative'],
    text: '',
    flavourText: '',
    internalNote: '',
    rarity: 1,
    damage: 2,
    health: 2
  },
  eratHerba: {
    name: 'Erat Herba',
    image: 'creature/nature/erat-herba.jpg',
    element: 'nature',
    icon: 'nature',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['dragon'],
    keywords: ['flying', 'aggressive', 'swift'],
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
    flavourText: '',
    internalNote: '',
    rarity: 4,
    damage: 0,
    health: 0
  },
  kyl: {
    name: 'Kyl',
    image: 'creature/frost/kyl-god-of-frost.jpg',
    element: 'frost',
    icon: 'frost',
    cost: DEFAULT_COST,
    type: 'god',
    subtypes: ['frost'],
    keywords: [],
    text: 'Whenever an enemy unit hurts me the turn it arrived, I permanently freeze it.',
    flavourText: '',
    internalNote: '',
    rarity: 3,
    damage: 0,
    health: 0
  },
  freezeling: {
    name: 'Freezeling',
    image: 'creature/frost/freezeling.jpg',
    element: 'frost',
    icon: 'frost',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['elemental'],
    keywords: ['flashfreeze', 'still'],
    text: '',
    flavourText: '',
    internalNote: '',
    rarity: 1,
    damage: 1,
    health: 2
  },
  frigus: {
    name: 'Frigus Mortis',
    image: 'creature/frost/frigus-mortis.jpg',
    element: 'frost',
    icon: 'frost',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['dragon'],
    keywords: ['flying'],
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
    flavourText: '',
    internalNote: '',
    rarity: 4,
    damage: 0,
    health: 0
  },
  apollyon: {
    name: 'Apollyon',
    image: 'creature/void/apollyon.jpg',
    element: 'void',
    icon: 'void',
    cost: DEFAULT_COST,
    type: 'god',
    subtypes: ['void'],
    keywords: [],
    text: "When I'm defeated, I turn target friendly mortal into a god.",
    flavourText: '',
    internalNote: '',
    rarity: 3,
    damage: 0,
    health: 0
  },
  drainling: {
    name: 'Drainling',
    image: 'creature/void/drainling.jpg',
    element: 'void',
    icon: 'void',
    cost: 2,
    type: 'unit',
    subtypes: ['elemental'],
    keywords: ['rupture', 'echoing'],
    text: '',
    flavourText: '',
    internalNote: '',
    rarity: 1,
    damage: 1,
    health: 2
  },
  terram: {
    name: 'Nullius Terram',
    image: 'creature/void/nullius-terram.jpg',
    element: 'void',
    icon: 'void',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['dragon'],
    keywords: ['flying'],
    text: '',
    flavourText: '',
    internalNote: '',
    rarity: 4,
    damage: 0,
    health: 0
  },
  elise: {
    name: 'Elise',
    image: 'creature/earth/elise-goddess-of-earth.jpg',
    element: 'earth',
    icon: 'earth',
    cost: DEFAULT_COST,
    type: 'god',
    subtypes: ['earth'],
    keywords: [],
    text: 'My armor is equal to the amount of friendly immortals I command.',
    flavourText: '',
    internalNote: '',
    rarity: 3,
    damage: 0,
    health: 0
  },
  crushling: {
    name: 'Crushling',
    image: 'creature/earth/crushling.jpg',
    element: 'earth',
    icon: 'earth',
    cost: 2,
    type: 'unit',
    subtypes: ['elemental'],
    keywords: ['landslide', 'sturdy'],
    text: '',
    flavourText: '',
    internalNote: '',
    rarity: 1,
    damage: 1,
    health: 2
  },
  armorillo: {
    name: 'Armorillo',
    image: 'creature/earth/armorillo.jpg',
    element: 'earth',
    icon: 'earth',
    cost: 2,
    type: 'unit',
    subtypes: ['armorillo'],
    keywords: [],
    text: '',
    flavourText: '',
    internalNote: '',
    rarity: 1,
    damage: 0,
    health: 0
  },

  earthGiant: {
    name: 'Giant',
    image: 'creature/earth/giant.jpg',
    element: 'earth',
    icon: 'earth',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['giant'],
    keywords: [],
    text: '',
    flavourText: '',
    internalNote: '',
    rarity: 3,
    damage: 0,
    health: 0
  },
  vitaDeserto: {
    name: 'Vita Deserto',
    image: 'creature/earth/vita-deserto.jpg',
    element: 'earth',
    icon: 'earth',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['dragon'],
    keywords: ['flying'],
    text: '',
    flavourText: '',
    internalNote: '',
    rarity: 4,
    damage: 0,
    health: 0
  },
  herald: {
    name: 'Herald',
    image: 'creature/lightning/herald.jpg',
    element: 'light',
    icon: 'light',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['beast'],
    keywords: [],
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
    flavourText: '',
    internalNote: '',
    rarity: 2,
    damage: 0,
    health: 0
  },
  ulwar: {
    name: 'Ulwar',
    image: 'creature/lightning/ulwar.jpg',
    element: 'dark',
    icon: 'dark',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['werewolf'],
    keywords: [],
    text: '',
    flavourText: '',
    internalNote: '',
    rarity: 2,
    damage: 0,
    health: 0
  },
  dither: {
    name: 'Dither',
    image: 'creature/void/giant.jpg',
    element: 'dark',
    icon: 'dark',
    cost: DEFAULT_COST,
    type: 'unit',
    subtypes: ['giant'],
    keywords: [],
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
    flavourText: '',
    internalNote: '',
    rarity: 3,
    damage: 0,
    health: 0
  },
  bulton: {
    name: 'Bulton',
    image: 'creature/earth/male-01.png',
    element: 'physical',
    icon: 'earth',
    cost: 4,
    type: 'unit',
    subtypes: ['mortal', 'humanoid', 'troll'],
    keywords: ['Single-Strike'],
    text: '',
    flavourText: '',
    internalNote: '',
    rarity: 1,
    damage: 4,
    health: 2
  },
  steelSword: {
    name: 'Steel Sword',
    image: 'equipment/sword.png',
    element: 'physical',
    icon: '',
    cost: undefined,
    type: 'relic',
    subtypes: ['equipment', 'one-handed'],
    keywords: ['Equip 1', 'Single-Strike'],
    text: '',
    flavourText: '',
    internalNote: '',
    rarity: 1,
    damage: 2,
    health: 0
  }
};

const applyScaling = (card: Card) => {
  // Do stuff
  return card;
};

export default (id: string | CardRef, fullBody: boolean = false, meta?: DynamicObject) =>
  applyScaling(
    entity(
      ALL_CARDS,
      typeof id === 'string' ? id : id.id,
      typeof id === 'string' ? undefined : id.uuid,
      fullBody,
      typeof id === 'string'
        ? meta?.overrides
        : meta?.overrides
          ? deepMerge(id.overrides || {}, meta.overrides || {})
          : id.overrides
    ) as Card
  ) as Required<Card>;
